name: Build and Deploy LaTeX Document
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: main.pdf

  deploy:
    runs-on: ubuntu-latest
    needs: build_latex
    permissions:
      contents: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: compiled-pdf
          path: . # Download to the current directory
      - name: Deploy to GitHub Pages
        run: |
          git config user.name "${{ secrets.USER_NAME }}"
          git config user.email "${{ secrets.USER_EMAIL }}"
          git fetch origin
          git switch --orphan gh-pages
          rm -rf * # Remove all files except .git
          cp main.pdf howard_resume.pdf
          echo "Resume compiled on ${{ github.event.head_commit.timestamp }}" > README.md
          git add howard_resume.pdf README.md
          git commit -m "Deploy resume compiled on ${{ github.event.head_commit.timestamp }}"
          git push -f origin gh-pages
